### ISSUE TITLE
Switch to Mapbox or improve map rendering

### ISSUE THREAD

**Issue by bascht** [hacken-in/hacken-in#552]
At the moment we're using [Leaflet](http://leafletjs.com/index.html) for rendering the maps – which is fine in terms of functionality – but the Maps look awful.

If we can improve the map rendering and stay with the OSM cards, I'm all for it.

Otherwise we could give Mapbox a try – I talked to @freenerd at yesterdays Devops meetup and I think they can arrange something if we bust the free plan of 3000 map views / month.

**Comment by freenerd** [comment]
We can probably arrange something. How about you play around with Mapbox, see if it fits your needs, and get back to me when you are sure you'll want to make the switch?

**Comment by bascht** [comment]
@freenerd We will! Let's see what @bitboxer and @moonglum think of it.

**Comment by moonglum** [comment]
That sounds pretty nifty! Thanks, @freenerd and @bascht

**Comment by freenerd** [comment]
We just increased the [free plan's map views/month limit](https://www.mapbox.com/plans/) from 3000 to 50.000. Hope this gives you some headroom for the switch :)

**Comment by bascht** [comment]
\*pokes\* @bitboxer

**Comment by bitboxer** [comment]
Yes, we can do that. Currently I am in the "fix all the bugs thing". Can't promisse when I will have time to try this out.

**Comment by bascht** [comment]
I just took some time to play around with Leaflet and it looks like we don't even have to switch Gems. I fiddled with the layers for homepage + event sites to reduce the visual clutter (and display public transport around the venue). Changes are in #270df54.

Lemme know what you think (left vs. right):
#### Homepage
![screenshot from 2015-08-16 16-43-17](https://cloud.githubusercontent.com/assets/51264/9293744/122e72e0-4437-11e5-9eec-3ef59b5ee034.png)
#### Events
![screenshot from 2015-08-16 16-43-51](https://cloud.githubusercontent.com/assets/51264/9293745/152b2d4e-4437-11e5-953c-9defd13b27fb.png)

**Comment by moonglum** [comment]
That looks AWESOME. Huge :+1: from me! (especially the homepage, niiice)

**Comment by freenerd** [comment]
Wow, so much cleaner :heart_eyes:

**Comment by bascht** [comment]
#615 was merged yesterday – we might re-do the homepage once Boston is up and things get too stretchy. :smile:
