### ISSUE TITLE
Setting up vagrant box: Unable to locate package ruby2.2.3

### ISSUE THREAD

**Issue by timomeh** [hacken-in/hacken-in#642]
Setting up the vagrant box fails:

```
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ruby2.2.3' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package ruby2.2.3
==> default: E: Couldn't find any package by regex 'ruby2.2.3'
```

... followed by a lot of _failed dependencies_ warnings.

Because `script/bootstrap` doesn't print the output of `vagrant up`, I ran it manually to see the errors. Maybe the output of `vagrant up` should be printed to the console. `vagrant up` takes some time and it's nice to see that he's doing _something_.

Reason could be: There's ruby2.2.4 in PPA, but not 2.2.3. Using 2.2 could fix this. (Actually @railsbros-dirk told me about this)

**Comment by bascht** [comment]
@timomeh Oh geeeeeeez. You are very right. :) Looking into it, right now.

**Comment by bascht** [comment]
@timomeh Once #643 is green, you could hit the merge button. :)

**Comment by timomeh** [comment]
Nice! \o/ Thanks

**Comment by timomeh** [comment]
Unfortunately, it still won't work.

```
==> default: Notice: /Package[ruby2.2.4-dev]: Dependency Package[ruby2.2.4] has failures: true
==> default: Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install ruby2.2.4' returned 100: Reading package lists...
==> default: Building dependency tree...
==> default: Reading state information...
==> default: E: Unable to locate package ruby2.2.4
==> default: E: Couldn't find any package by regex 'ruby2.2.4'
```

Maybe it has to do something with the default yaml?

```
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
```

Because it fails with:

```
==> default: Running provisioner: puppet...
==> default: Running Puppet with default.pp...
==> default: stdin: is not a tty
==> default: /usr/lib/ruby/vendor_ruby/puppet/defaults.rb:465: warning: duplicated key at line 466 ignored: :queue_type
==> default: /usr/lib/ruby/vendor_ruby/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>'
==> default: : 
==> default: uninitialized constant Syck
```

But actually I have no idea ¯\_(ツ)_/¯

**Comment by railsbros-dirk** [comment]
Manually install Ruby with

```
sudo apt-get install ruby2.2=2.2.4*
```

worked fine. Why did 2.2.3 worked before? Did BrightBox change the repo layout?

**Comment by bascht** [comment]
Oh my. That looks like it is part of a larger problem (Puppet not being able to get their shit together and support Ruby 2.x).

Installing Ruby 2.2 via interactive apt (that is `running apt-get manually`) will probably set the default Ruby to 2.x – leaving Puppet no chance to bootstrap. 

Just out of sheer curiosity: Can you check `which ruby`?

**Comment by timomeh** [comment]
```
$ which ruby
/usr/bin/ruby

$ ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]
```

But this is after manually installing ruby2.2.4. I'll destroy the box and set it up later.

**Comment by timomeh** [comment]
With a fresh (ruby2.2.4-failing) setup:

```sh
$ which ruby
/usr/bin/ruby
$ ruby --version
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]
```

**Comment by bascht** [comment]
@timomeh @railsbros-dirk I've hard-wired the Ruby Version which should at least fix the failing install. Could you retry? (`vagrant destroy -f; ./script/bootstrap`)?

**Comment by timomeh** [comment]
Yep, the ruby problem is solved. But: Vagrant stopped out of nowhere after setting up nginx (I think that's the last thing puppet does?). Then he exited without any error, just _»The SSH command responded with a non-zero exit status.«_. So he didn't execute `HACKEN_BOOTSTRAP`, which runs `bundle ...`.

I can run the last commands manually, but `bundle install` takes so freaking long and it got late after one hour of setting up. 😅 I'll try to install them tomorrow and check if it finally works.

**Comment by timomeh** [comment]
After running `bundle install --path=vagrant/vendor` and `bundle exec rake db:migrate` manually, I get a database error in http://hacken.local. 😟

```
PG::UndefinedTable: ERROR:  relation "region_slugs" does not exist
LINE 5:                WHERE a.attrelid = '"region_slugs"'::regclass
```

From app/controllers/application_controller.rb, Line #54 

Did I miss something, maybe the databse not being setup properly in provisioning?

**Comment by bascht** [comment]
Sounds like you're almost there. (hacken.in is famous for leaving no Gem behind, so the first bundler run will take a bit :grin:) – bundle-installing-it right now. Will report back. ;)

**Comment by bascht** [comment]
→ #644 :)

**Comment by bascht** [comment]
@timomeh The future arrived at hacken.in – so if you're feeling lucky: Could you retry with our latest and greatest Docker dev environment?

See https://github.com/hacken-in/hacken-in#getting-started for hints & let us know if you have problems setting it up?

**Comment by timomeh** [comment]
Awesome! I'll try it out in the next days. 🙂
