### ISSUE TITLE
ActionView::Template::Error in sitemap#show

### ISSUE THREAD

**Issue by moonglum** [hacken-in/hacken-in#662]
## Error in Hacken.in

**ActionView::Template::Error** in **sitemap#show**
No route matches {:action=>"show", :controller=>"single_events", :event_id=>nil, :id=>"48104"} missing required keys: [:event_id]

[View on Bugsnag](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5725fda7768f9c6f8ea20e8e?event_id=58ac320aaf051a11002ae910)

## Stacktrace

    app/views/sitemap/show.xml.erb:12 - block in _app_views_sitemap_show_xml_erb__1639894221213806191_70277399828180
    app/views/sitemap/show.xml.erb:10 - _app_views_sitemap_show_xml_erb__1639894221213806191_70277399828180
    app/controllers/sitemap_controller.rb:7 - show

[View full stacktrace](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5725fda7768f9c6f8ea20e8e?event_id=58ac320aaf051a11002ae910)

**Comment by bascht** [comment]
Bulletin from our department of database consistency:

```
[42] pry(main)> SingleEvent.find(48104).event_id
=> 600
[43] pry(main)> SingleEvent.find(48104).event_id
=> nil
```

Which gets gobbled up by

```
def show
    @single_events = SingleEvent.all
    respond_with @single_events
  end
```

**Comment by bascht** [comment]
Fixed by our magic database fairies. https://hacken.in/sitemap.xml
