### ISSUE TITLE
RuntimeError in twitter:follow

### ISSUE THREAD

**Issue by moonglum** [hacken-in/hacken-in#711]
## Error in Hacken.in

**RuntimeError** in **twitter:follow**
Problems following nextlevelconf No user matches for specified terms.

[View on Bugsnag](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5949854dab8cde0018ae4466?event_id=5949854dab8cde0018ae4465&i=gh&m=ci)

## Stacktrace

    lib/twitter_follower.rb:15 - rescue in block in follow
    lib/twitter_follower.rb:11 - block in follow
    lib/twitter_follower.rb:9 - each
    lib/twitter_follower.rb:9 - follow
    lib/tasks/twitter.rake:5 - block (2 levels) in <top (required)>

[View full stacktrace](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5949854dab8cde0018ae4466?event_id=5949854dab8cde0018ae4465&i=gh&m=ci)

**Comment by bascht** [comment]
Triggered while debugging #710

**Comment by moonglum** [comment]
An error linked to this issue has been reopened in Bugsnag
[**RuntimeError** in **twitter:follow**](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5949854dab8cde0018ae4466?event_id=5949ca62dd1a98001990a0b4&i=gh&m=ra)

**Comment by moonglum** [comment]
Repaired 👋
