### ISSUE TITLE
Twitter::Error::Unauthorized in twitter:follow

### ISSUE THREAD

**Issue by moonglum** [hacken-in/hacken-in#712]
## Error in Hacken.in

**Twitter::Error::Unauthorized** in **twitter:follow**
Could not authenticate you.

[View on Bugsnag](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5949856dc0ff2000180cae65?event_id=5949856dc0ff2000180cae64&i=gh&m=ci)

## Stacktrace

    lib/twitter_follower.rb:33 - block in following
    lib/twitter_client.rb:18 - request_wrapper
    lib/twitter_follower.rb:32 - following
    lib/twitter_follower.rb:21 - not_followed_handles
    lib/twitter_follower.rb:9 - follow
    lib/tasks/twitter.rake:5 - block (2 levels) in <top (required)>

[View full stacktrace](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5949856dc0ff2000180cae65?event_id=5949856dc0ff2000180cae64&i=gh&m=ci)

**Comment by bascht** [comment]
Calm down, automated @moonglum. 'twas but me.

**Comment by moonglum** [comment]
Real @moonglum is happy that fake @moonglum is watching 👌

**Comment by bascht** [comment]
Triggered while debugging #710.

**Comment by moonglum** [comment]
An error linked to this issue has been reopened in Bugsnag
[**Twitter::Error::Unauthorized** in **twitter:follow**](https://app.bugsnag.com/hacken-dot-in/hacken-dot-in/errors/5949856dc0ff2000180cae65?event_id=5949ca66dd3d160018b2f3d4&i=gh&m=ra)

**Comment by moonglum** [comment]
I manually ran the twitter follow script. It works again 👍
